Features/modal for blocklists condition
amehmeto/TiedSiren51 pull request #13
Opened 2024-09-26 12:12 UTC by myatthiri98

2024-09-26 21:22 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +                iconName={condition.iconName as keyof typeof Ionicons.glyphMap}
The as keyof typeof Ionicons.glyphMap is a type assertion that might not be necessary if condition.iconName can be properly typed.

Instead of casting, check if the type of condition.iconName can be inferred correctly. If CONDITIONS or condition.iconName isn't properly typed, it would be better to address the typing at the source. Overusing as can introduce bugs since TypeScript won't validate the cast.

I try to avoid `as` as much as possible. I see it as a code smell.

2024-09-26 21:29 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +function ConditionItem({
The name "Item" is too generic and doesn't communicate enough about its purpose or business domain. It's in the same category as names like data, array, or var1, which are often too ambiguous for others to understand the context.

In this case, something more specific, like "Condition" or "BlockingCondition", would align better with the domain and intent. This not only helps developers but also makes the code more readable, ideally by non-developers who might work with the business side.

Well-crafted, meaningful names make the code more self-explanatory and reduce the cognitive load for anyone maintaining it in the future. Strive for clarity and intent in naming!

2024-09-26 21:37 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +        size={24}
Magic number here. What happen if we need to change the size of all the icon in the future? ;) 

Feel free to use the closest number available in the general theme ( T ), and if nothing make sense, you can create a new variable in the theme.

2024-09-26 21:38 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +})
Fantastic job using the general theme from the design system!

2024-09-26 21:55 UTC, amehmeto requested changes
Well done on this job! I noticed that you quickly grasped my coding style, and you did a great job applying it. Consistency like this is crucial for maintainability and readability, so it’s great to see you pick it up so fast.

I have a few comments that might help you take your skills even further. ;)

There is one significant improvement I’d like to mention: you should have reused the existing TSModal component. This component is already aligned with our design system, and reusing it would ensure consistency across the project. When you need to create a new component, it's always a good idea to check if something similar already exists. If it doesn't meet all your needs, it's often better to extend the existing component rather than building something from scratch—though this isn't a strict rule and depends on the situation.

Keep up the great work, and I’m confident these small adjustments will help you continue to grow!

2024-09-26 21:55 UTC, amehmeto commented on ui/screens/Blocklists/shared/BlocklistForm.tsx
> +          setModalVisible(true)
This onPress event handler starts to be fat, it makes sense to me to extract the arrow function. When you when to extract something (either variable or function, or really anything), I strongly recommend to use the functionality of your IDE. That's a shortcut I use daily, it's very very useful!

Also don't leave commented out code. Either use it or delete it. Leaving commented code is dead code, and that's dirty.

2024-09-26 21:55 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +const ROUTE_TABS = '/(tabs)'
It would be better to make an enum. An enum makes it very convenient to type as well. Whenever I came across a bunch of constants that fits well together as a group, I use an enum.

2024-09-26 21:55 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +          listType={LIST_TYPE_DEVICES}
Well done extracting my magic strings ;)

2024-09-27 04:30 UTC, myatthiri98 commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +function ConditionItem({
I've addressed the feedback from the code review and pushed the changes.
 Could you please take another look? Thanks!

2024-09-27 14:48 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +              <BlockingConditionComponent
Nope, Component is again a technical term. Normally, any React developper *already knows* it's a component.

Just like with "Item," names like "Component" don't provide enough meaning or context. I'd suggest sticking with `BlockingCondition` for now, as it better reflects the business logic and makes the code more readable.

Secondly, and more importantly, using the index as a key in a list is a major anti-pattern in React. While it works in some cases, it can lead to serious performance and rendering issues, especially if the list items are reordered or filtered. React relies on keys to efficiently update the DOM, and using index can cause unnecessary re-renders or incorrect behavior.

Instead, try to use a unique identifier from condition, like condition.title or condition.id, if available. This helps React keep track of the elements more accurately.

2024-09-27 14:49 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +}: BlockingConditionComponentProps) {
Same comment about the name. BlockingConditionProps would be enough.

2024-09-27 14:53 UTC, amehmeto commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +  React.useEffect(() => {
It's more readable to use `useEffect` straightaway than `React.useEffect`.

I want to see how this animation will workout! :)

2024-09-27 14:54 UTC, amehmeto requested changes
I left

2024-09-27 15:19 UTC, myatthiri98 commented on ui/design-system/components/components/BlockingConditionModal.tsx
> +              <BlockingConditionComponent
Thank you for the detailed feedback! 
I’ve made the suggested changes:
Renamed the component to BlockingCondition for better clarity.
Replaced the use of the index as a key with condition.title to ensure unique and stable keys.

2024-09-27 20:57 UTC, amehmeto approved these changes

2024-09-27 20:57 UTC, merged