feat: add data validation for blocklist form and block session form
amehmeto/TiedSiren51 pull request #15
Opened 2024-09-28 16:37 UTC by myatthiri98

2024-09-28 18:13 UTC, amehmeto commented on ui/screens/Blocklists/BlocklistForm.tsx
> +  const [errors, setErrors] = useState<{ [key: string]: string }>({})
{ [key: string]: string } should be extracted into a type alias

2024-09-28 18:15 UTC, amehmeto commented on ui/screens/Blocklists/BlocklistForm.tsx
> +    // marginTop: 4,
dead code

2024-09-28 18:19 UTC, amehmeto commented on ui/screens/Home/shared/BlockSessionForm.tsx
> +      !blockingCondition
The condition you’ve written is a bit complex and would benefit from being extracted into its own function. This improves readability by removing the implementation details from the main logic and gives the condition a clear, meaningful name.

For example, you could create a function named hasSomeEmptyField(), which clearly communicates the intent of the check:

```
function hasSomeEmptyField() {
  return (
    !name ||
    blocklists.length === 0 ||
    devices.length === 0 ||
    !startedAt ||
    !endedAt ||
    !blockingCondition
  );
}
```

2024-09-28 18:21 UTC, amehmeto commented on ui/screens/Home/shared/BlockSessionForm.tsx
>            }
You can simplify this block and improve readability by using early returns. This avoids unnecessary nesting and makes the control flow easier to follow. Here's an example:

try {
  // some logic
} catch (e) {
  if (!(e instanceof z.ZodError)) {
    return {}
  }

  const errors: { [key: string]: string } = {}
  e.errors.forEach((error) => {
    const field = error.path[0] as string
    errors[field] = error.message
  })
  return errors
}

For more info: https://medium.com/codex/early-return-in-typescript-explained-along-with-how-i-use-it-in-react-apps-92c0694a8356

2024-09-28 18:26 UTC, amehmeto commented on ui/screens/Home/shared/BlockSessionForm.tsx
> +          router.push('/(tabs)')
Actually I have a personal preference for ternary. This more concise and readable.

Also I try to never use else: https://dev.to/dglsparsons/write-better-code-and-be-a-better-programmer-by-never-using-else-statements-4dbl?utm_source=pocket_shared

2024-09-28 18:26 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +  // console.log('Touched fields:', props.form.touched)
dead code

2024-09-28 18:27 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +        {props.form.touched.name && props.form.errors.name && (
That's a long condition that I don't really understand if I didn't code it myself. It needs to be extracted with a meaningful name such as hasFormErrors for instance

2024-09-28 18:29 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +              <Text key={index} style={styles.errorText}>
Never ever use index as a key. This is a major fault with react. 

The condition is too long and make the code difficult to read. You should take the habit to extract condition

2024-09-28 18:30 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +                {typeof error === 'string' ? error : JSON.stringify(error)}
This should be extracted in a constant as well

2024-09-28 18:32 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +        {props.form.touched.startedAt && props.form.errors.startedAt && (
That's always the same pattern. This condition could be refactored into a function to avoid duplication

2024-09-28 18:41 UTC, amehmeto requested changes
There is some duplication to remove. Also I am a big fan of extraction, and code readability.

So that would be the changes I would request.

Well done for the good work!

2024-10-03 01:16 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +          }
Why did you choose to change that? I guess you had a reason, but I don't really understand.

2024-10-03 02:45 UTC, amehmeto approved these changes

2024-10-03 02:46 UTC, merged

2024-10-03 03:18 UTC, myatthiri98 commented on ui/screens/Home/shared/SelectBlockSessionParams.tsx
> +          }
I made this change because I wanted to transform the selectedDevices data structure before passing it to the form. 
By explicitly mapping the selectedDevices to only include id and name, I aimed to ensure that the form only stores the relevant information. 
This helps keep the form data clean and avoids storing unnecessary details. 
If there’s a better way to handle this, I’d love to hear your thoughts.