Feature/authentication screen
amehmeto/TiedSiren51 pull request #17
Opened 2024-10-01 15:17 UTC by myatthiri98

2024-10-10 05:31 UTC, amehmeto commented on app/(auth)/login.tsx
> +    <TiedSLinearBackground>
I think the TiedSLinearBackground can now be moved to _layout.tsx

It's true for every screens. That's the purpose of _layout, to get everything in common at the same place

2024-10-10 05:35 UTC, amehmeto commented on app/(auth)/login.tsx
> +          }
I don't like component nested into other components. That's how a code can get messy over time and difficult to read.

I advice you to create a component and extract it.

2024-10-10 05:36 UTC, amehmeto commented on app/(auth)/login.tsx
> +          }
Same comment here

2024-10-10 05:38 UTC, amehmeto commented on app/(auth)/login.tsx
> +          secureTextEntry={!showPassword}
A conventional way to name a boolean value, is to prefix it with is or has. In this case here, it would be a better fit to name it isPasswordShown or isPasswordDisplayed for instance.

2024-10-10 05:39 UTC, amehmeto commented on app/(auth)/login.tsx
> +        />
Nested component into a component again ;)

2024-10-10 05:49 UTC, amehmeto commented on app/(auth)/login.tsx
> +          style={styles.button}
I think there is already a style applied to the button, that's why the prop style is optional. Is the additional style necessary ?

2024-10-10 05:51 UTC, amehmeto commented on app/(auth)/signup.tsx
> +          }
Nested component

2024-10-10 05:51 UTC, amehmeto commented on app/(auth)/signup.tsx
> +          }
Nested component

2024-10-10 05:52 UTC, amehmeto commented on app/(auth)/signup.tsx
> +          }
TouchableOpacity is deprecated. I believe I am the one that have introduced it first, but it was a mistake. Feel free to change it for Pressable instead.

2024-10-10 05:56 UTC, amehmeto commented on app/_layout.tsx
>    }, [])
Well done extracting a growing useEffect, I think you start getting my logic ;)

2024-10-10 06:00 UTC, amehmeto commented on app/_layout.tsx
> +
Here you can flip the if-else statement as such:

```
if (!store) return
initializeBackgroundTasks(store)
navigateBasedOnAuth()
```

That's called an early return, and it prevent nested if-else, and nested code that become difficult to read when code is accumulated over time

Also, as navigateBasedOnAuth isn't dependent on store, you can put it above the condition.

2024-10-10 06:04 UTC, amehmeto commented on app/_layout.tsx
> +  }
When using try-catch, it's better to wrap the whole body of the function. For further reading: https://stackoverflow.com/a/18794993/11698446

2024-10-10 06:06 UTC, amehmeto commented on app/_layout.tsx
> +  }
Using const for function is perfectly fine. You will come across it in many project. But my personal preference is to use the `function` keyword. There is nothing wrong with const, it's just a preference.

Remember to try to stick to the code style of the project when you join a company ;)

2024-10-10 06:10 UTC, amehmeto commented on app/_layout.tsx
>            <Stack.Screen name="(tabs)" />
This could be extracted.

You can create an array of routes and map over them such as:

const routes = ['(auth)/register', '(auth)/login', ..., '(tabs)']

return (
  <Provider ... >
    {routes.map(route => <Stack.Screen name={route} /> )}
  </Provider>

2024-10-10 06:11 UTC, amehmeto commented on ui/design-system/components/shared/BlockingConditionModal.tsx
> +    opacity.value = visible ? 1 : 0
Great refactoring, way more readable and concise

2024-10-10 06:13 UTC, amehmeto commented on ui/design-system/components/shared/TiedSTextInput.tsx
>      </View>
Well done updating the core component of the design system!

2024-10-10 06:16 UTC, amehmeto commented on ui/screens/Home/shared/SelectBlockingCondition.tsx
It's an old code coming from a git rebase I guess, but it's not important. Yet here, we can also get rid of TouchableOpacity in favor of Pressable

2024-10-10 06:17 UTC, amehmeto requested changes
A lot of good things, I'm impressed!

Thank you very much for this work.

I've added my comments as usual ;)

2024-10-12 08:15 UTC, myatthiri98 commented on app/(auth)/login.tsx
> +          style={styles.button}
Thank you for the feedback! 
I’ve made the style prop optional to allow for additional customization, particularly for adjusting the padding. 
I believe this will enhance the overall appearance and usability for users. Let me know if you have any further thoughts!

2024-10-12 08:34 UTC, myatthiri98 commented on app/_layout.tsx
> +
thanks , I totally understand now

2024-10-12 09:07 UTC, myatthiri98 commented on app/_layout.tsx
> +  }
Thanks a lot for your details explanation.

2024-10-12 09:10 UTC, myatthiri98 commented on ui/screens/Home/shared/SelectBlockingCondition.tsx
Thanks a lot for your details explanation

2024-10-13 18:05 UTC, amehmeto commented on app/(auth)/login.tsx
> +          hasPasswordToggle={true}
That's cool

2024-10-13 18:14 UTC, amehmeto approved these changes

2024-10-13 18:14 UTC, merged