Fix/resolve iOS tab icons issue and stabilize time zone-dependent tests
amehmeto/TiedSiren51 pull request #19
Opened 2024-10-18 15:21 UTC by myatthiri98

2024-11-17 16:52 UTC, amehmeto requested changes

2024-11-24 23:22 UTC, amehmeto requested changes

2024-11-24 23:22 UTC, amehmeto commented on ui/design-system/components/shared/TiedSCloseButton.tsx
> +    >
No need for that, the previous 
onPress={onClose}> 
was good enough and more concise

2024-11-24 23:22 UTC, amehmeto commented on app/(tabs)/_layout.tsx
> +    // height: T.tabBarHeight,
Don't leave commented out code behind, that's a bad practice. Never ever do that

2024-11-25 12:06 UTC, myatthiri98 commented on app/(tabs)/_layout.tsx
> +    // height: T.tabBarHeight,
Noted with thanks

2024-11-25 12:58 UTC, amehmeto approved these changes

2024-11-25 12:58 UTC, merged